[package]
name = "asterism-service"
version = "0.1.0"
authors = ["hercules-network"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = { version = "1.0.41" }
hex-literal = "0.3.1"
futures = { version = "0.3.13" }
log = { version = "0.4.11" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

# asterism
quark-runtime = { path = "../../runtime/quark" }
hadron-runtime = { path = "../../runtime/hadron" }
asterism-rpc = { path = "../rpc" }
lyra-primitives = { git = "https://github.com/hercules-network/lyra.git" }

# substrate client
sc-cli = { version = "0.9.0", features = ["wasmtime"] }
sc-executor = { version = "0.9.0", features = ["wasmtime"] }
sc-service = { version = "0.9.0", features = ["wasmtime"] }
sc-transaction-pool = { version = "3.0.0" }
sc-consensus-aura = { version = "0.9.0" }
sc-consensus = { version = "0.9.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-client-api = { version = "3.0.0" }
sc-rpc = { version = "3.0.0" }
sc-rpc-api = { version = "0.9.0" }
sc-telemetry = { version = "3.0.0" }
sc-keystore = { version = "3.0.0" }
sc-chain-spec = { version = "3.0.0" }
sc-basic-authorship = { version = "0.9.0" }

# substrate primitives
sp-core = { version = "3.0.0" }
sp-inherents = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0"}
sp-consensus-aura = { version = "0.9.0" }
sp-consensus = { version = "0.9.0" }
sp-finality-grandpa = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }
sp-api = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
sp-block-builder = { version = "3.0.0" }
sp-offchain = { version = "3.0.0" }
sp-session = { version = "3.0.0" }
sp-storage = { version = "3.0.0" }
sp-trie = { version = "3.0.0" }

frame-benchmarking = { version = "3.0.0" }
frame-benchmarking-cli = { version = "3.0.0" }

# pallet
substrate-frame-rpc-system = { version = "3.0.0" }
substrate-prometheus-endpoint = { version = "0.9.0" }
pallet-transaction-payment-rpc = { version = "3.0.0" }
pallet-staking-rpc = { git = "https://github.com/hercules-network/lyra.git" }
pallet-contracts-rpc = { version = "3.0.0" }
pallet-contracts = { version = "3.0.0" }

# EVM
pallet-evm = { default-features = false, path = "../../pallets/evm" }
fc-consensus = { path = "../../client/consensus" }
fp-consensus = { path = "../../primitives/consensus" }
fc-rpc-core = { path = "../../client/rpc-core" }
fp-rpc = { path = "../../primitives/rpc" }

# API
frame-system-rpc-runtime-api = { version = "3.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0" }

[build-dependencies]
substrate-build-script-utils = '3.0.0'
# frame-benchmarking-cli = { version = '3.0.0', optional = true }

[features]
default = ["db", "full-node"]

db        = ["sc-service/db"]
full-node = []

dev = [
    "quark-runtime/dev",
    "hadron-runtime/dev",
]

runtime-benchmarks = [
    "quark-runtime/runtime-benchmarks",
    "hadron-runtime/runtime-benchmarks",
]